### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by lidarwin** [sagor999/poker_ml#2]
In  `poker_ml/expected_value/src/main.rs`

There are paths to files that don't exist with one such example: `combinations.bin` in
`  let combinations_path: String =   "/home/pavel/nvme/GitHub/poker_ml/expected_value/data/combinations.bin".to_string();`

When running `./poker_ev` there is then an error that says cannot find file and directory

Maybe these were files that you meant to include in your project?

**Comment by sagor999** [comment]
This line checks if that file exists, and if not, it will generate it and save:
https://github.com/sagor999/poker_ml/blob/60d75e164930b2b03da7ed96d054062ba1173883/expected_value/src/main.rs#L1066

It takes a bit of time to generate it, and I did not want to submit it into git as it is about 100MB in size.

**Comment by sagor999** [comment]
Oh, also update the path to match your env. :) I should have fixed to make that path relative, but never got to it.

**Comment by lidarwin** [comment]
> This line checks if that file exists, and if not, it will generate it and save:
> 
> https://github.com/sagor999/poker_ml/blob/60d75e164930b2b03da7ed96d054062ba1173883/expected_value/src/main.rs#L1066
> 
> It takes a bit of time to generate it, and I did not want to submit it into git as it is about 100MB in size.

I did change the paths so that all the paths match my working directory in main.rs but the files never got generated

Is it the `cargo build --release` step that generates these files?

**Comment by sagor999** [comment]
Oh, that's odd. I guess for some reason that check returns that file exists?
You can try to add output to see what that `exists()` function returns.

`cargo build --release` creates executable in release configuration. you need to run `cargo run` to run the executable, or you can just manually execute the binary as well.

**Comment by lidarwin** [comment]
> Oh, that's odd. I guess for some reason that check returns that file exists? You can try to add output to see what that `exists()` function returns.
> 
> `cargo build --release` creates executable in release configuration. you need to run `cargo run` to run the executable, or you can just manually execute the binary as well.

Turns out that I mistyped my directories. This step seems to be fine now. However I suggest adding in the instructions to run the command `cargo update -p lexical-core` If running a newer version of rust. That’s what I had to do to get `cargo build —release to work`

**Comment by lidarwin** [comment]
> > Oh, that's odd. I guess for some reason that check returns that file exists? You can try to add output to see what that `exists()` function returns.
> > `cargo build --release` creates executable in release configuration. you need to run `cargo run` to run the executable, or you can just manually execute the binary as well.
> 
> Turns out that I mistyped my directories. This step seems to be fine now. However I suggest adding in the instructions to run the command `cargo update -p lexical-core` If running a newer version of rust. That’s what I had to do to get `cargo build —release to work`

Ok, I realized I needed to install nvidia environment for docker, so this part is okay now. Thanks!
