### ISSUE TITLE
ImportError: ImageGrab is macOS and Windows only

### ISSUE THREAD

**Issue by lidarwin** [sagor999/poker_ml#4]
https://github.com/sagor999/poker_ml/blob/60d75e164930b2b03da7ed96d054062ba1173883/orchestrator/main.py#L1

When I do `make run` in the root folder, I get this issue:

`python3 orchestrator/main.py
Traceback (most recent call last):
  File "orchestrator/main.py", line 1, in <module>
    from PIL import Image, ImageGrab, ImageChops, ImageOps
  File "/usr/lib/python3/dist-packages/PIL/ImageGrab.py", line 26, in <module>
    raise ImportError("ImageGrab is macOS and Windows only")
ImportError: ImageGrab is macOS and Windows only
make: *** [Makefile:5: run] Error 1
`

Is this meant to be ran in Windows/macOS terminals after creating all the files in Linux?

**Comment by sagor999** [comment]
Hm. Nope, it was definitely working in Linux. 
My guess is that something changed with `ImageGrab` package and they only suport win & mac now. try to see if you can use earlier version of `PIL`.

**Comment by kodyvoyles** [comment]
I know this is a dead section did some modifying to get most of it working had to modify the dockerfiles a little bit.

Anyways. I'm getting this error now when doing a make run
